# Generated by Django 3.2.6 on 2021-09-11 17:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210911_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonetoken',
            options={'verbose_name': 'otp token', 'verbose_name_plural': 'otp tokens'},
        ),
        migrations.AlterField(
            model_name='phonetoken',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='attempts'),
        ),
        migrations.AlterField(
            model_name='phonetoken',
            name='otp',
            field=models.CharField(editable=False, max_length=40, verbose_name='otp'),
        ),
        migrations.AlterField(
            model_name='phonetoken',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(editable=False, max_length=128, region=None, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='phonetoken',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='phonetoken',
            name='used',
            field=models.BooleanField(default=False, verbose_name='used'),
        ),
        migrations.AlterModelTable(
            name='phonetoken',
            table='phone_token',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
